# Generated by Django 5.0.14 on 2026-09-30 15:38

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analyses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('area_m2', models.FloatField()),
                ('index', models.IntegerField()),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('centroid', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='analyses.analysis')),
            ],
            options={
                'verbose_name': 'building',
                'verbose_name_plural': 'buildings',
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='RoofGeometry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tilt_deg', models.FloatField()),
                ('azimuth_deg', models.FloatField()),
                ('usable_area_m2', models.FloatField()),
                ('source', models.CharField(max_length=64)),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('building', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='roof', to='geospatial.building')),
            ],
            options={
                'verbose_name': 'roof geometry',
                'verbose_name_plural': 'roof geometries',
            },
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['analysis', 'index'], name='geospatial__analysi_f70483_idx'),
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['analysis', 'area_m2'], name='geospatial__analysi_98ea0b_idx'),
        ),
    ]
