# Generated by Django 5.0.14 on 2026-09-30 15:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analyses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('geojson', 'GeoJSON'), ('csv', 'CSV'), ('pdf', 'PDF')], max_length=16)),
                ('storage_key', models.CharField(blank=True, max_length=512, null=True)),
                ('checksum', models.CharField(blank=True, max_length=64, null=True)),
                ('bytes', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='analyses.analysis')),
            ],
            options={
                'verbose_name': 'export artifact',
                'verbose_name_plural': 'export artifacts',
                'ordering': ['-created_at'],
            },
        ),
    ]
