# Generated by Django 5.0.14 on 2026-09-30 15:38

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analyses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageryAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(max_length=64)),
                ('storage_key', models.CharField(max_length=512)),
                ('checksum', models.CharField(max_length=64)),
                ('crs', models.CharField(max_length=64)),
                ('resolution_m', models.FloatField(blank=True, null=True)),
                ('bounds', models.JSONField(blank=True, default=dict)),
                ('bands', models.PositiveIntegerField(default=0)),
                ('acquired_at', models.DateTimeField(blank=True, null=True)),
                ('footprint', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagery_assets', to='analyses.analysis')),
            ],
            options={
                'verbose_name': 'imagery asset',
                'verbose_name_plural': 'imagery assets',
                'ordering': ['-created_at'],
            },
        ),
    ]
