# Generated by Django 5.0.14 on 2026-09-30 14:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("action", models.CharField(max_length=100)),
                (
                    "actor_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                (
                    "target_type",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("target_id", models.CharField(blank=True, default="", max_length=64)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-at"],
                "indexes": [
                    models.Index(
                        fields=["action", "-at"], name="audit_audit_action_6fe893_idx"
                    ),
                    models.Index(
                        fields=["target_type", "target_id"],
                        name="audit_audit_target__59bbff_idx",
                    ),
                ],
            },
        ),
    ]
