# Generated by Django 5.0.14 on 2026-09-30 15:38

import django.contrib.gis.db.models.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='draft', max_length=16)),
                ('idempotency_key', models.CharField(blank=True, max_length=200, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('snapshot', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'analysis',
                'verbose_name_plural': 'analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisArea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('area', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name': 'analysis area',
                'verbose_name_plural': 'analysis areas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisAssumption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('measured', 'Measured'), ('inferred', 'Inferred'), ('user', 'User'), ('default', 'Default'), ('calculated', 'Calculated')], default='default', max_length=16)),
                ('usable_roof_fraction', models.FloatField(default=0.7)),
                ('power_density_w_m2', models.FloatField(default=200.0)),
                ('system_losses', models.FloatField(default=0.14)),
                ('module_eff', models.FloatField(default=0.2)),
                ('tilt_deg', models.FloatField(default=20.0)),
                ('azimuth_deg', models.FloatField(default=180.0)),
                ('shading', models.FloatField(default=1.0)),
                ('temp_air', models.FloatField(default=20.0)),
                ('wind', models.FloatField(default=1.0)),
            ],
            options={
                'verbose_name': 'analysis assumption',
                'verbose_name_plural': 'analysis assumptions',
                'ordering': ['-created_at'],
            },
        ),
    ]
