# Generated by Django 5.0.14 on 2026-09-30 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analyses', '0001_initial'),
        ('ml_models', '0001_initial'),
        ('projects', '0001_initial'),
        ('solar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='calculation_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analyses', to='solar.calculationmethodversion'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='model_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analyses', to='ml_models.mlmodelversion'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='projects.project'),
        ),
        migrations.AddField(
            model_name='analysisarea',
            name='analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='analyses.analysis'),
        ),
        migrations.AddField(
            model_name='analysisassumption',
            name='analysis',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assumption', to='analyses.analysis'),
        ),
        migrations.AddConstraint(
            model_name='analysis',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('project', 'idempotency_key'), name='uq_analysis_project_idempotency_key'),
        ),
    ]
