# Generated by Django 5.0.14 on 2026-09-30 15:38

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analyses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=16)),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('worker_info', models.JSONField(blank=True, default=dict)),
                ('provenance', models.JSONField(blank=True, default=dict)),
                ('queued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.JSONField(blank=True, null=True)),
                ('cancel_requested', models.BooleanField(default=False)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job', to='analyses.analysis')),
            ],
            options={
                'verbose_name': 'processing job',
                'verbose_name_plural': 'processing jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(choices=[('validate_request', 'Validate request'), ('load_imagery', 'Load imagery'), ('validate_raster', 'Validate raster'), ('tile', 'Tile imagery'), ('segment', 'Segment (U-Net inference)'), ('postprocess_mask', 'Post-process mask'), ('extract_polygons', 'Extract polygons'), ('solar_calc', 'Solar calculation'), ('persist_results', 'Persist results'), ('prepare_report', 'Prepare report')], max_length=32)),
                ('sequence', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=16)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='jobs.processingjob')),
            ],
            options={
                'verbose_name': 'job stage',
                'verbose_name_plural': 'job stages',
                'ordering': ['sequence'],
            },
        ),
        migrations.AddConstraint(
            model_name='jobstage',
            constraint=models.UniqueConstraint(fields=('job', 'name'), name='uq_jobstage_job_name'),
        ),
    ]
