"""Generate deterministic synthetic sample data for the sample/offline path.

Produces:
    - ``sample-data/sample_imagery.tif``: a 512x512, 3-band uint8 GeoTIFF in a
      real UTM CRS (EPSG:32632) with a valid affine transform, containing a few
      bright rectangular "roofs" on a darker background.
    - ``sample-data/sample_area.geojson``: an analysis-boundary polygon covering
      the raster, in EPSG:4326.
    - ``sample-data/README.md``: provenance, license, checksums, CRS, transform,
      and expected output ranges.

The data is fully synthetic (CC0 / public domain). Deterministic via a fixed seed.

Usage:
    python scripts/generate_sample_data.py
"""

from __future__ import annotations

import hashlib
import json
import logging
from pathlib import Path

import numpy as np
import rasterio
from rasterio.transform import from_origin
from rasterio.warp import transform_bounds

logger = logging.getLogger(__name__)

_SEED = 20240930
_SIZE = 512
_RES_M = 0.5  # metres per pixel
_CRS = "EPSG:32632"  # UTM zone 32N
_ORIGIN_EASTING = 500_000.0
_ORIGIN_NORTHING = 5_400_000.0  # ~ 48.75N, near UTM 32N central meridian
_BACKGROUND = 55
_ROOF = 225

_SAMPLE_DIR = Path(__file__).resolve().parents[1] / "sample-data"
_TIF_PATH = _SAMPLE_DIR / "sample_imagery.tif"
_GEOJSON_PATH = _SAMPLE_DIR / "sample_area.geojson"
_README_PATH = _SAMPLE_DIR / "README.md"

# (row0, col0, height_px, width_px) rectangles -> bright roofs.
_ROOFS: tuple[tuple[int, int, int, int], ...] = (
    (60, 60, 80, 120),
    (200, 300, 100, 100),
    (380, 120, 70, 160),
    (300, 60, 40, 40),
)


def _build_image(rng: np.random.Generator) -> np.ndarray:
    """Build a 3-band uint8 image array shaped ``(3, H, W)``."""
    base = np.full((_SIZE, _SIZE), _BACKGROUND, dtype=np.float64)
    base += rng.normal(0.0, 6.0, size=base.shape)
    for row0, col0, height, width in _ROOFS:
        patch = rng.normal(_ROOF, 8.0, size=(height, width))
        base[row0 : row0 + height, col0 : col0 + width] = patch
    band = np.clip(base, 0, 255).astype(np.uint8)
    # Slight per-band variation so R, G, B are not identical.
    red = band
    green = np.clip(band.astype(np.int16) - 10, 0, 255).astype(np.uint8)
    blue = np.clip(band.astype(np.int16) - 20, 0, 255).astype(np.uint8)
    return np.stack([red, green, blue], axis=0)


def _sha256(path: Path) -> str:
    """Return the lowercase hex SHA-256 digest of ``path``."""
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1 << 20), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _write_geotiff(image: np.ndarray, transform: rasterio.Affine) -> None:
    """Write the 3-band image to a GeoTIFF with the given transform and CRS."""
    with rasterio.open(
        _TIF_PATH,
        "w",
        driver="GTiff",
        height=_SIZE,
        width=_SIZE,
        count=3,
        dtype="uint8",
        crs=_CRS,
        transform=transform,
    ) as dst:
        dst.write(image)


def _write_boundary(transform: rasterio.Affine) -> None:
    """Write an EPSG:4326 boundary polygon covering the whole raster."""
    left = transform.c
    top = transform.f
    right = left + _SIZE * _RES_M
    bottom = top - _SIZE * _RES_M
    west, south, east, north = transform_bounds(
        _CRS, "EPSG:4326", left, bottom, right, top
    )
    ring = [
        [west, south],
        [east, south],
        [east, north],
        [west, north],
        [west, south],
    ]
    feature_collection = {
        "type": "FeatureCollection",
        "crs": {"type": "name", "properties": {"name": "urn:ogc:def:crs:EPSG::4326"}},
        "features": [
            {
                "type": "Feature",
                "properties": {"label": "sample analysis area"},
                "geometry": {"type": "Polygon", "coordinates": [ring]},
            }
        ],
    }
    _GEOJSON_PATH.write_text(json.dumps(feature_collection, indent=2))


def _expected_roof_area_m2() -> float:
    """Return the total roof area (m^2) implied by the drawn rectangles."""
    px_area = _RES_M * _RES_M
    return sum(h * w for _, _, h, w in _ROOFS) * px_area


def _write_readme(transform: rasterio.Affine) -> None:
    """Write the provenance/README document for the sample data."""
    tif_sha = _sha256(_TIF_PATH)
    geojson_sha = _sha256(_GEOJSON_PATH)
    total_area = _expected_roof_area_m2()
    content = f"""# Sample Data

Deterministic synthetic sample data for the Rooftop Energy Estimator
offline/sample path and tests.

## Provenance & License

- **Source:** synthetic / generated by `scripts/generate_sample_data.py`
  (seed `{_SEED}`). No real imagery is used.
- **License:** CC0 1.0 (public domain). This is fabricated data; it depicts no
  real location and carries no third-party rights.

## Files

| File | SHA-256 |
|------|---------|
| `sample_imagery.tif` | `{tif_sha}` |
| `sample_area.geojson` | `{geojson_sha}` |

## `sample_imagery.tif`

- **Dimensions:** {_SIZE} x {_SIZE} px, 3 bands (R, G, B), `uint8`.
- **CRS:** {_CRS} (UTM zone 32N).
- **Resolution:** {_RES_M} m/px.
- **Affine transform:** `{tuple(round(v, 6) for v in transform[:6])}`
  (a, b, c, d, e, f) => origin (easting, northing) =
  ({transform.c}, {transform.f}).
- **Content:** {_BACKGROUND}-ish dark background with {len(_ROOFS)} bright
  ({_ROOF}-ish) rectangular "roofs".

## `sample_area.geojson`

- **CRS:** EPSG:4326.
- A single rectangular polygon covering the full raster footprint.

## Expected output ranges

Running the segmentation + vectorization pipeline on this imagery (with the tiny
CI model, results are approximate; with the real model, closer to ground truth):

- **Roof polygons (ground truth):** {len(_ROOFS)}.
- **Total roof area (ground truth):** ~{total_area:.0f} m^2.
- Individual roof areas range from
  ~{min(h * w for _, _, h, w in _ROOFS) * _RES_M * _RES_M:.0f} to
  ~{max(h * w for _, _, h, w in _ROOFS) * _RES_M * _RES_M:.0f} m^2.

All small ground-truth roofs are >= the pipeline's 20 m^2 minimum-area filter.
"""
    _README_PATH.write_text(content)


def main() -> None:
    """Generate all sample-data artifacts deterministically."""
    _SAMPLE_DIR.mkdir(parents=True, exist_ok=True)
    rng = np.random.default_rng(_SEED)
    transform = from_origin(_ORIGIN_EASTING, _ORIGIN_NORTHING, _RES_M, _RES_M)
    image = _build_image(rng)
    _write_geotiff(image, transform)
    _write_boundary(transform)
    _write_readme(transform)
    logger.info(
        "sample data generated",
        extra={
            "tif": str(_TIF_PATH),
            "geojson": str(_GEOJSON_PATH),
            "readme": str(_README_PATH),
        },
    )


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    main()
