# Generated by Django 5.0.14 on 2026-09-30 15:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MLModelVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('version', models.CharField(max_length=64)),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('training_dataset_version', models.CharField(blank=True, max_length=128)),
                ('preprocess_config', models.JSONField(default=dict)),
                ('input_resolution', models.PositiveIntegerField(default=256)),
                ('signature', models.JSONField(default=dict)),
                ('metrics', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('candidate', 'Candidate'), ('registered', 'Registered'), ('production', 'Production'), ('rolled_back', 'Rolled back')], default='candidate', max_length=16)),
                ('mlflow_run_id', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'verbose_name': 'ML model version',
                'verbose_name_plural': 'ML model versions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='mlmodelversion',
            constraint=models.UniqueConstraint(fields=('name', 'version'), name='uq_mlmodelversion_name_version'),
        ),
    ]
