# Generated by Django 5.0.14 on 2026-09-30 15:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geospatial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationMethodVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='solar', max_length=64)),
                ('version', models.CharField(max_length=64)),
                ('parameters', models.JSONField(default=dict)),
                ('description', models.TextField(blank=True)),
                ('effective_date', models.DateField()),
            ],
            options={
                'verbose_name': 'calculation method version',
                'verbose_name_plural': 'calculation method versions',
                'ordering': ['-effective_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SolarEstimate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('capacity_kwp', models.FloatField()),
                ('annual_kwh', models.FloatField()),
                ('monthly_kwh', models.JSONField(default=list)),
                ('specific_yield', models.FloatField()),
                ('usable_area_m2', models.FloatField()),
                ('inputs', models.JSONField(default=dict)),
                ('disclaimer', models.TextField(default='These are engineering estimates for indicative purposes only and are not a bankable photovoltaic yield study.')),
            ],
            options={
                'verbose_name': 'solar estimate',
                'verbose_name_plural': 'solar estimates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='calculationmethodversion',
            constraint=models.UniqueConstraint(fields=('name', 'version'), name='uq_calcmethod_name_version'),
        ),
        migrations.AddField(
            model_name='solarestimate',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solar_estimates', to='geospatial.building'),
        ),
        migrations.AddField(
            model_name='solarestimate',
            name='calculation_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estimates', to='solar.calculationmethodversion'),
        ),
    ]
